// Writes a TypeScript ABI module from a compiled Cairo contract class.
// Usage: bun scripts/gen-starknet-abi.ts <contract_class.json> <ExportName> <out.ts>
import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

const [source, exportName, out] = process.argv.slice(2);
if (!source || !exportName || !out) {
  console.error("usage: bun scripts/gen-starknet-abi.ts <contract_class.json> <ExportName> <out.ts>");
  process.exit(1);
}
const contractClass = JSON.parse(readFileSync(source, "utf8"));
const abi = typeof contractClass.abi === "string" ? JSON.parse(contractClass.abi) : contractClass.abi;
writeFileSync(
  out,
  `// Generated by scripts/gen-starknet-abi.ts from ${basename(source)}. Do not edit by hand.\n` +
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
